### ISSUE TITLE
Upload feature not working

### ISSUE THREAD

**Issue by cbalbinos** [Aravindha1234u/typebot-railway#1]
I am unable to use Typebot's upload feature

I added the S3 variables, from a Minio that I also installed using the Railway template

S3_ACCESS_KEY=TJJTMGYBQXXXXXXXXXXX
S3_SECRET_KEY=xsWH4Po9AtEGJEYZB93clFGDtszdfYXXXXXXXXXXXXXX
S3_BUCKET=typebot
S3_ENDPOINT=console-production-dc8c.up.railway.app

Am I doing something wrong?

**Comment by cbalbinos** [comment]
I tested it with a Minio installed on the Digital Ocean and it worked, but with the Minio installed on the Railway I was unsuccessful

I created the bucket with Access Policy = Public and the access key as I did in Digital Ocean and informed the console domain in S3_ENDPOINT

Where can I be going wrong?

**Comment by Aravindha1234u** [comment]
Can you please give me some time to check on this feature? I haven't tested it

**Comment by cbalbinos** [comment]
Of course. Thank you for your feedback

**Comment by Aravindha1234u** [comment]
Hi, @cbalbinos I just want some more information on this issue. So you used my template to deploy Typebot. You tried to configure S3 upload feature with Minio from the railway itself and I assume you add another service within the template for Minio Console am I right? I believe you configured all the required variables according to [builder docs](https://docs.typebot.io/self-hosting/configuration/builder#s3-storage-media-uploads) and [viewer docs](https://docs.typebot.io/self-hosting/configuration/viewer#s3-storage-file-upload-input), but it didn't work. However, when you connected to Minio outside the railway platform like the Digital ocean you mentioned here it worked for you am I right? then I guess it should something with railway service configuration

**Comment by cbalbinos** [comment]
Correct, I did the test with Digital Ocean after registering the problem here.  It seems that the problem is with the Railway.  

An observation, for me to use Minio in DO it was necessary to leave port 9000 exposed, in Railway I don't know how this works.

**Comment by Aravindha1234u** [comment]
Yes, Minio uses two ports 9000 for S3-like protocol communication and 9001 for web dashboard. Railway doesn't allow you to expose multiple ports with different domain names that's what I know, but does it still fail over Railway's internal network over ipv6? Have you tried it?

**Comment by cbalbinos** [comment]
No, how can I do this?

**Comment by Aravindha1234u** [comment]
Checkout here: https://docs.railway.app/reference/private-networking

**Comment by cbalbinos** [comment]
In the Minio console variables, this url is informed in CONSOLE_MINIO_SERVER

I also informed this and the console domain

![image](https://github.com/Aravindha1234u/typebot-railway/assets/91399681/d5b1ad69-c9e3-44bf-9420-ec84b65f427d)

**Comment by cbalbinos** [comment]
I also tried with Private Networking

**Comment by cbalbinos** [comment]
with and without :9000

**Comment by Aravindha1234u** [comment]
can I get a picture or outline how you have setup your services with variable. you can mask the secret values but keep the domain and host information as such.

**Comment by cbalbinos** [comment]
I used the addresses below in CONSOLE_MINIO_SERVER

console

bucket

bucket:9000

console-production-dc8c.up.railway.app

console.railway.internal

bucket-production-d080.up.railway.app

bucket.railway.internal


Now I'm using these from Minio that are on Digital Ocean

![image](https://github.com/Aravindha1234u/typebot-railway/assets/91399681/51d203cf-2da1-4339-b705-407be49f6f8f)

**Comment by Aravindha1234u** [comment]
why do you have two services called bucket and console? and S3_ENDPOINT shows storage which I am not aware about that services. I am not sure which docker images are you using but if you use bitnami it should only one service which has console and bucket with two ports which makes it easier. 

https://hub.docker.com/r/bitnami/minio/

**Comment by cbalbinos** [comment]
Bucket and Console is what appears on the Minio installed with the Railway template.  

If you can install it to see how it works, it might be easier to understand and even simulate the problem I faced with the Minio installed on the Railway

**Comment by Aravindha1234u** [comment]
are you taking about this template? https://railway.app/template/SMKOEA
if so I guess you have to check with them. 

Railway's internal network will work only within a single project and not between two different projects I guess you are trying to achieve that.

**Comment by cbalbinos** [comment]
It is this template. I will check with them.

The Typebot template is working correctly with MInio installed on Digital Ocean.

Thank you for your attention!

**Comment by Aravindha1234u** [comment]
Thank you. If possible give a star to the repo.
