### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by cbalbinos** [Aravindha1234u/typebot-railway#2]
Hi @Aravindha1234u 

Some people who watched a content on YouTube where I show the installation of Typebot on Railway reported that it is showing the error Internal Server Error when accessing the builder

I did a fresh install here, and the error was also displayed

=========================
﻿
Using Detected Dockerfile
﻿
=========================
﻿
﻿
context: bf048ee8b6da4f93788806cc790756d5
﻿
ERROR: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
﻿

[LOG.txt](https://github.com/Aravindha1234u/typebot-railway/files/12430373/LOG.txt)

**Comment by cbalbinos** [comment]
Hi @Aravindha1234u , did you see what is happening with a new installation of Typebot?

**Comment by Aravindha1234u** [comment]
Hi @cbalbinos 
which error you are referring to DOCKER DAEMON is so it should railway issue you should contact them. Based on logs I see you haven't see some environment URL probably that's why its not working.

**Comment by cbalbinos** [comment]
Hi, this internal server error is occurring for new installations in Typebot with its template, when trying to scess the builder.  did you notice that there too?

**Comment by cbalbinos** [comment]
Well, I'll register the problem on Railway's Discord to see what they tell us

**Comment by Aravindha1234u** [comment]
Yes that could be helpful and I am there in discord you can pull me in if you want 
T3cH_W1z4rD#5916

**Comment by Aravindha1234u** [comment]
Sync the latest code or redeploy the template.

**Comment by lacctaone11** [comment]
"500
Internal Server Error." in viewer
