### ISSUE TITLE
Internal Server Error in viewer

### ISSUE THREAD

**Issue by cbalbinos** [Aravindha1234u/typebot-railway#3]
I received reports that now Typebot installed with the Railway template is showing the Internal Server Error in the viewer.

I created a new Typebot and it presented the error here too, I noticed that in the share tab the address is presented as localhost

![typebot_localhost](https://github.com/Aravindha1234u/typebot-railway/assets/91399681/691bc63d-06f4-41b0-9d36-01f3b3a4170b)

In the Theme and Settings tabs of the builder, the message Error! Couldn't initiate the chat.

**Comment by cbalbinos** [comment]
Replaced the latest version with 2.16 in my repository and the problem was fixed, so the problem is being caused by changes in 2.17 which brings WhatsApp integration

![typebot_localhost](https://github.com/Aravindha1234u/typebot-railway/assets/91399681/e516587f-ab6f-40ee-857a-67a11b151c3b)

**Comment by Aravindha1234u** [comment]
Yes its something wit the latest code. I am not sure which what happened last time as well. let's wait until they push a stable version.
