### ISSUE TITLE
Error on install on railway

### ISSUE THREAD

**Issue by michaelvips** [Aravindha1234u/typebot-railway#4]
I made everthing but I get 500 ERROR SERVER
![Screenshot_1](https://github.com/Aravindha1234u/typebot-railway/assets/21130174/c374d4fd-7096-4f22-82cb-b1f5c8ceb987)

**Comment by Aravindha1234u** [comment]
@michaelvips Yes there seems to be a issue in type bot latest version if you can downgrade the version to 2.17 it should work. Since this is neither in my hand or railway we have to wait until typebot releases new version with fixes
